### ISSUE TITLE
H168A da nasıl yaparım

### ISSUE THREAD

**Issue by emirh4ntnc** [BoomBookTR/ZXHN-H298A-V1.0-Modem-Root-Permission-Batch-Script#1]
Selam, bu yaptığın bat sosyasını herşeyi doğru yapıp çalıştırdım fakat xml dosyası boştu. Sonradan fark ettim ki bu H298A tür modem içinmiş , ben H168A kullanıyorum bu modelde yapabilirmiyim acaba ve boş olmasının sebebi model farkı mı

**Comment by BoomBookTR** [comment]
evet. Onunla ilgili script yazarının çalışması vardı galiba. Gelişme yok diye kalmış aklımda.

**Comment by Erencikefe** [comment]
Bende H168a V2 var decode yapamıyorum, yardomco olabilir misiniz?
