### ISSUE TITLE
root şifresi

### ISSUE THREAD

**Issue by openwebkey** [BoomBookTR/ZXHN-H298A-V1.0-Modem-Root-Permission-Batch-Script#2]
H298A V9 için bu scriptinizi uyguladım. Root şifresine ne yazmalıyım?

**Comment by BoomBookTR** [comment]
> H298A V9 için bu scriptinizi uyguladım. Root şifresine ne yazmalıyım?

Şu an desteklemiyor bildiğim kadarıyla.
