### ISSUE TITLE
root sifresi

### ISSUE THREAD

**Issue by r0darz** [BoomBookTR/ZXHN-H298A-V1.0-Modem-Root-Permission-Batch-Script#3]
Islemleri yaptim geri yukledim ama root sifresi ne hala bilmiyorum? Herhangi bir xml dosyasi da yok.

**Comment by BoomBookTR** [comment]
gerekli dosyaları indirir ve kurar. 
ilk önce modem içerisinden config dosyanızı indirin.
Scripti python vb. dosyasıyla birlikte indirin. Eksik olmasın. Scriptin bulunduğu klasöre config dosyanızı atın. 
Modem içerisinden serialinizi kopyalayın ve 1-PRESS_HERE.bat dosyasına tıklayın.
Zaten sizi yönlendirecektir. Uygun yerde modem serialini soracaktır. Girdikten sonra otomatik olarak xml yapar. O sırada root şifrenizi alırsınız ki nette de var zaten. Root şifresi altta:
`$F1r1@dl`
