### ISSUE TITLE
hata

### ISSUE THREAD

**Issue by ssssssdsad** [BoomBookTR/ZXHN-H298A-V1.0-Modem-Root-Permission-Batch-Script#4]
modem seri numarasını gir diyince giriyorum entere basıyorum kapanıyor direk 
değiştirdi sanıyorum config dosyasını modem arayüzüne atıyorum hiç birşey olmuyor

**Comment by BoomBookTR** [comment]
> modem seri numarasını gir diyince giriyorum entere basıyorum kapanıyor direk değiştirdi sanıyorum config dosyasını modem arayüzüne atıyorum hiç birşey olmuyor

Dosya/klasör yollarında boşluk ya da türkçe karakter var mı?
Bunlar hataya sebep olabilir. 

Yine Python gerekli olduğundan indirmeniz gerekiyor yok ise. Python kurulması konusunda zaten size soruyor.
O aşamaları doğruca evet diyerek geçiniz.

**Comment by BoomBookTR** [comment]
Modem bu değil mi? 
ZXHN H298A V1.0

**Comment by ssssssdsad** [comment]
https://prnt.sc/DpJTQrFM156I bu modemden değilmi V1.0 yazmıyor sadece o yüzdenmi

**Comment by BoomBookTR** [comment]
> https://prnt.sc/DpJTQrFM156I bu modemden değilmi V1.0 yazmıyor sadece o yüzdenmi

Modem içerisinden bakabilir misiniz?

![image](https://user-images.githubusercontent.com/10184695/208699962-8fd8bfa9-9f05-4403-9e2d-c9fd2e92f32c.png)

**Comment by ssssssdsad** [comment]
> 

https://prnt.sc/AMPcpDl-az5e  V1.0.  Aynı Attığınız SS ile

**Comment by BoomBookTR** [comment]
> > 
> 
> https://prnt.sc/AMPcpDl-az5e V1.0. Aynı Attığınız SS ile Hocam Discord : Halil#2116 bu benim ordan teamviewer verebilirim

Yazdım Discorddan.
