### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by gurselk** [BoomBookTR/ZXHN-H298A-V1.0-Modem-Root-Permission-Batch-Script#5]
Mac işletim sistemi için paylaşabilir misiniz bir tane

**Comment by BoomBookTR** [comment]
> Mac işletim sistemi için paylaşabilir misiniz bir tane

Mac işletim sistemiyle ilgili donanıma sahip değilim.
Mac sisteme python kurup gerekli komutları tek tek girebilirsiniz ya da mevcut kodun prensiplerini kullanarak mac için varsa alternatif kod yazabilirsiniz.

Kod basit düzeyde alttaki şekilde olmalı. Bunu editlerseniz sanırım çalışır. Python falan kurduğunuzu düşünerek kısa kod bu.
:zcumodule
:pipinstall
:pycryptodomexinstall
bölümlerini python kurulumu sonrası manuel yaptığını varsayıyorum.




`#!/bin/bash

# config.xml export
echo "Modem seri numaranızı girin: "
read -r serial_number
python examples/decode.py --serial "$serial_number" config.bin config.xml | grep -i "Successfully decoded using serial"
if [ $? -eq 0 ]; then
    echo "config.xml EXPORT tamamlandı."
else
    echo "HATA: Seri numarası yanlış! Doğru seri numarasını girin."
    exit 1
fi

# replace.py kontrolü ve indirme
if [ -e replace.py ]; then
    echo "replace.py bulundu."
else
    echo "replace.py bulunamadı, indiriliyor..."
    curl -O https://raw.githubusercontent.com/BoomBookTR/ZXHN-H298A-V1.0-Modem-Root-Permission-Batch-Script/main/replace.py
fi

# replace.py çalıştırma
python replace.py

# config.xml import
echo "config.bin import zamanı!"
python examples/encode.py --serial "$serial_number" --signature "ZXHN H298A V1.0" config.xml config.bin | grep -i "Done"
if [ $? -eq 0 ]; then
    echo "config.xml IMPORT tamamlandı."
else
    echo "HATA: Seri numarası yanlış! Doğru seri numarasını girin."
    exit 1
fi

echo "Tüm işlemler tamamlandı. config.bin dosyanızı modem arayüzünden geri yükleyebilirsiniz."
`
