### ISSUE TITLE
SSH Erişim Olmuyor

### ISSUE THREAD

**Issue by lgkoyuncu** [BoomBookTR/ZXHN-H298A-V1.0-Modem-Root-Permission-Batch-Script#6]
Cihaza root şifresi ile login olabiliyorum ama ssh cevap vermiyor.

**Comment by BoomBookTR** [comment]
O konuda bilgim yok. Bu script sadece modemdeki root hesabını etkinleştirmeye yarıyor. SSH desteği olmayabilir.

**Comment by cektor** [comment]
Merhaba bende çalışmadı pythonu indirdi kurdu ama orda takıldı bir zaman geçtikten sonra komut satırı kendiliğinden kapandı ama bir işlem olmadı modem seri no sorma ekranı gelmedi

**Comment by BoomBookTR** [comment]
> Merhaba bende çalışmadı pythonu indirdi kurdu ama orda takıldı bir zaman geçtikten sonra komut satırı kendiliğinden kapandı ama bir işlem olmadı modem seri no sorma ekranı gelmedi.
> Not: 2-PRESS_HERE.bat yi de denedim yine olmadı

Bu script robot hesabını etkinleştirmek ve girebilmek için. SSH belki bu modelde etkin olmayabilir.

**Comment by BoomBookTR** [comment]
> Merhaba bende çalışmadı pythonu indirdi kurdu ama orda takıldı bir zaman geçtikten sonra komut satırı kendiliğinden kapandı ama bir işlem olmadı modem seri no sorma ekranı gelmedi. Not: 2-PRESS_HERE.bat yi de denedim yine olmadı

2-PRESS_HERE.bat için sıkıntı varsa 1-PRESS_HERE.bat ile devam edebilirsiniz. O daha basit python kurulumunu sonra eklemiştim.
